name: Fresh Commit
on: workflow_dispatch

permissions: write-all

jobs:
    commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: lazuee/github-fresh-commit@1.0.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: "${{ github.ref }}"
                  # Uncomment below to custom commit message. (default: latest commit message)
                  # commit_message: "First commit"
